### ISSUE TITLE
Is it possible to update react native?

### ISSUE THREAD

**Issue by brasilikum** [francisrod01/RNwithoutExpo#1]
Oi Francis,

Thank you for your article and this repo. I currently find myself in a situation where expo is causing more issues than it's solving.

You write in your Article that it does not work to update to the latest version of react-native. Is there any reason why a normal update process would not work on this repo? 
Could I update react-native and all dependencies?

Best
Georg

**Comment by francisrod01** [comment]
Hi Georg, how are you doing?
First of all, I'm Francis, not Francisco ;p
Second, you could give it a try yourself and see how it works. It's just something I've noticed in React Native resources since it was created.

In case you're going to use it in a private or commercial project which you need help, maybe I can support you.

My best.


Francis Rodrigues

Software Engineer, Owner of a Travel Platform, Travel writer, Tech writer
My Travel website: https://bestamericas.travel/
Mentoring Profile: https://codementor.io/francisrod01/
LinkedIn: https://linkedin.com/in/francisrod01/
Medium: https://medium.com/@francis.rod01/
Twitter: https://twitter.com/francisrod01
Instagram: https://instagram.com/rod01francis

________________________________

**Comment by brasilikum** [comment]
Ha, you were fast! I changed within the first minute after writing :)
Ok, fair point. I will check it out and report back.

Best
